# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cod', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=128)),
                ('tipo', models.CharField(choices=[('Chefe', 'Chefe'), ('Administrativo', 'Administrativo')], max_length=25)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translado_app.Departamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cnh', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RespSolicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translado_app.Motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataH_inicio', models.DateTimeField(blank=True, null=True)),
                ('dataH_fim', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(max_length=128)),
                ('destino', models.CharField(max_length=128)),
                ('motivo', models.CharField(max_length=128)),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translado_app.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('modelo', models.CharField(max_length=35)),
                ('ano', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='respsolicitacao',
            name='solicitacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='translado_app.Solicitacao'),
        ),
        migrations.AddField(
            model_name='respsolicitacao',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translado_app.Veiculo'),
        ),
    ]
